### ISSUE TITLE
Backlight does not work for tasks.

### ISSUE THREAD

**Issue by darkprof83** [tomtom/viki_vim#18]
Thank you for your plugin. Backlight does not work for tasks.  No error messages are output.
![2017-10-18 14-25-44](https://user-images.githubusercontent.com/4998392/31712028-5c318dde-b413-11e7-9fa2-322cf9b5c253.png)

**Comment by tomtom** [comment]
The correct syntax is

    #A1 2017-10-18 test task 1

Without the hyphen.

**Comment by darkprof83** [comment]
ok, without the hyphen not work too
`Linux darkhost 4.13.7-1-ARCH #1 SMP PREEMPT Sat Oct 14 20:13:26 CEST 2017 x86_64 GNU/Linux`
`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  7 2017 13:52:29)
Included patches: 1-1176`
and tested on
`Linux darkprof-VirtualBox 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:14:44 UTC 2017 i686 athlon i686 GNU/Linux`
`VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056`
![2017-10-18_22-46-46](https://user-images.githubusercontent.com/4998392/31733900-6402eeb6-b456-11e7-870b-19fffbea848d.png)

**Comment by tomtom** [comment]
> ok, without hyphen not work too

Is there a reason why you don't want to switch to 
<https://github.com/tomtom/vikibase_vim>? The old viki plugin is 
actually abandoned.

**Comment by darkprof83** [comment]
Thanks did not know that the highlighting of tasks in it works. I can not undestanding with hyperlinks. \<leader\>vf not work in it and :map do not contains vikibase_vim keys.

**Comment by tomtom** [comment]
The idea of vikibase plugin is to handle just the syntax highlighting and some other basic stuff. Hyperlinks are handled by the autolinker_vim plugin that also knows how to handle interviki definitions. Folding is handled by the foldtext_vim plugin. One thing that's still missing is file listings though -- in case you used that feature. All in all this separation makes the whole thing easier to maintain.

Please let me know if vikibase and friends doesn't solve your problem.

**Comment by darkprof83** [comment]
Thanks. Yeh, solved.
